[[redirects]]
from = "/favicon.ico"
to = "/favicon.svg"
status = 200

[[redirects]]
from = "/api/*"
to = "https://dotsoflove-production.up.railway.app/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
